### ISSUE TITLE
Server Backend?

### ISSUE THREAD

**Issue by Jesse-longname** [Jesse-longname/gtc17#15]
Two reasons... More secure, and be able to use a more traditional database more easily. 
I'm thinking a Flask backend would be best, since it uses Python (Which would already be used for the data scripts), and it is SUPER simple to setup. 

I'll make a branch to start working on this, and let me know if there are any objections.

**Comment by Jesse-longname** [comment]
Started work in the `server-backend` branch

**Comment by ian-whitestone** [comment]
I think this can be closed?
